In [1]:
# Exercise 6: Broadcasting and Slicing
## Use of for loop is not allowed here

In [2]:
## Q1: Generate a 2D (9X9), with all elements initialized to 1 and of type int8

In [12]:
import numpy as np
arr_2D = np.ones((9,9), dtype=np.int8)
print("The 2D (9x9) array:\n", arr_2D)

The 2D (9x9) array:
 [[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [13]:
## Q2: Create a 2D pattern using slicing

In [35]:
pattern = arr_2D.copy()
pattern[1:-1, 1:-1] = 0
pattern[2:-2, 2:-2] = 1
pattern[3:-3, 3:-3] = 0
pattern[4:-4, 4:-4] = 1

print("Pattern array:\n", pattern)

Pattern array:
 [[1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 0 1 0 1 0 1]
 [1 0 1 0 0 0 1 0 1]
 [1 0 1 1 1 1 1 0 1]
 [1 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1]]


In [15]:
## Q3: Using broadcasting create an output matrix based on the following two arrays:
# array_1 = np.array([1,2,3,4,5], dytpe=np.int8)
# array_2 = np.array([1,2,3], dytpe=np.int8)

In [29]:
array_1 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
array_2 = np.array([1, 2, 3], dtype=np.int8)
# output = array_1.reshape(-1, 1) * array_2.reshape(1, -1)
output = array_1[:, None] * array_2[None, :]
print("Output matrix:\n", output)

Output matrix:
 [[ 1  2  3]
 [ 2  4  6]
 [ 3  6  9]
 [ 4  8 12]
 [ 5 10 15]]
