In [1]:
# Exercise 9: Football Tournament

In [9]:
import numpy as np
from itertools import combinations, permutations

# Load the actual model forecasts data
model_forecasts = np.loadtxt('model_forecasts.txt', delimiter=',')

# Replace nan values on diagonal with 0 (teams don't play against themselves)
np.fill_diagonal(model_forecasts, 0)

print("Model forecasts matrix:")
print(model_forecasts)
print(f"Matrix shape: {model_forecasts.shape}")

def find_optimal_pairing(forecasts):
    """
    Find the optimal pairing that minimizes sum of squared differences.
    Uses combinations to select 5 teams for first group, then finds best permutation pairing.
    """
    n_teams = forecasts.shape[0]
    teams = list(range(n_teams))
    
    min_sum_squared_diff = float('inf')
    best_pairing = None
    
    print("Searching for optimal pairing...")
    
    # Generate all ways to choose 5 teams for the first group
    for group1 in combinations(teams, 5):
        group2 = tuple(t for t in teams if t not in group1)
        
        # Try all permutations of group2 to pair with group1
        for perm2 in permutations(group2):
            sum_squared_diff = 0
            for i in range(5):
                diff = forecasts[group1[i], perm2[i]]
                sum_squared_diff += diff ** 2
            
            if sum_squared_diff < min_sum_squared_diff:
                min_sum_squared_diff = sum_squared_diff
                best_pairing = np.array([list(group1), list(perm2)])
    
    return best_pairing, min_sum_squared_diff

# Find the optimal pairing
optimal_pairing, min_score = find_optimal_pairing(model_forecasts)

print(f"\nOptimal pairing found:")
print(optimal_pairing)
# print(f"Minimum sum of squared differences: {min_score:.2f}")

# # Verify the matches and their score differences
# print("\nMatch details:")
# for i in range(5):
#     team1, team2 = optimal_pairing[0, i], optimal_pairing[1, i]
#     diff = model_forecasts[team1, team2]
#     print(f"Match {i+1}: Team {team1} vs Team {team2}, Score difference: {diff:.2f}, Squared: {diff**2:.2f}")


Model forecasts matrix:
[[ 0.   -2.3  -4.59 -4.83  3.13  4.13  1.07  2.29  0.44  4.35]
 [ 2.3   0.    3.57 -4.66  2.3  -3.24  3.63  0.41 -2.   -0.77]
 [ 4.59 -3.57  0.    1.47  1.15 -1.16  4.97  4.81  1.86  1.5 ]
 [ 4.83  4.66 -1.47  0.    0.25 -1.9  -0.14  3.89  4.34 -1.42]
 [-3.13 -2.3  -1.15 -0.25  0.    3.9  -2.73  1.23 -4.16  3.33]
 [-4.13  3.24  1.16  1.9  -3.9   0.   -0.5   2.96 -2.69 -4.48]
 [-1.07 -3.63 -4.97  0.14  2.73  0.5   0.    4.42 -1.35 -3.95]
 [-2.29 -0.41 -4.81 -3.89 -1.23 -2.96 -4.42  0.    4.49 -0.4 ]
 [-0.44  2.   -1.86 -4.34  4.16  2.69  1.35 -4.49  0.    2.29]
 [-4.35  0.77 -1.5   1.42 -3.33  4.48  3.95  0.4  -2.29  0.  ]]
Matrix shape: (10, 10)
Searching for optimal pairing...

Optimal pairing found:
[[0 1 2 3 5]
 [8 7 9 4 6]]
