In [1]:
# Exercise 7: NaN

In [6]:
# Simulate data
import numpy as np

generator = np.random.default_rng(123)
grades = np.round(generator.uniform(low = 0.0, high = 10.0, size = (10, 2)))

grades[[1,2,5,7], [0,0,0,0]] = np.nan
# np.where(condition, value_if_true, value_if_false)
third_col = np.where(np.isnan(grades[:,0]), grades[:,1], grades[:, 0])

# Append as new column
grades_with_third = np.column_stack([grades, third_col])
print(grades_with_third)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [nan  2.  2.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [ 8.  5.  8.]]
