In [4]:
# Exercise 4: Random

In [5]:
import numpy as np

# set seed
np.random.seed(888)

In [3]:
## Q1: 1D normal distribution (size 100)

In [9]:
normal_1d = np.random.randn(100)
print("Normal 1D shape:\n", normal_1d)

Normal 1D shape:
 [ 0.6159096   0.03134465 -1.08335867 -1.66608962 -0.43977505 -1.57969972
 -0.02106819  0.86440243  0.22212128  0.81250355 -0.20449472  1.52039379
  0.64022257 -1.99299568  0.24737691  0.18463455 -0.24192008 -1.59246798
  1.45999652 -1.4263102  -0.34836611  0.33996734  0.43484765 -0.52116545
 -0.86253277  1.19945472  0.81274993 -0.56333516  0.34712438  0.3566236
 -1.10326573 -0.92059849 -0.75848109  0.90175291  0.66719533  0.3099234
  0.31522152  0.38941639  0.29040943 -0.34098103 -0.57719171  0.09588328
 -0.8062309  -0.03486154  0.49498914 -0.02204072 -0.00640163 -2.01272543
  1.51474911  0.52014338  1.28364896 -0.6278823   1.34317566  0.43830268
  0.76131657 -0.0453198  -0.20386984 -0.75524572  0.36024241 -1.41316516
 -0.37785324  0.94768519  2.25162786  0.69431341 -0.99728526  0.97922457
  0.2147672   0.37312693 -0.69246705 -0.44906754 -0.11945879 -0.53801271
 -0.25293928  0.61233673  0.48491548 -1.78745503  0.78335477 -0.15175686
 -1.31884318 -0.04141261 -0.1033755

In [ ]:
## q2: 2D random integers 1-10 (8x8)

In [11]:
rand_int_2d = np.random.randint(1, 11, size=(8,8))
print("2D Integers 8by8 shape:\n", rand_int_2d)

2D Integers 8by8 shape:
 (8, 8)


In [15]:
## Q3: 3D random integers 1-17 (4,2,5)
print("3D integers array:\n", np.random.randint(1, 18, size=(4, 2, 5)))

3D integers array:
 [[[14  2 12  7 13]
  [ 1  8  5  7  5]]

 [[ 4 11  7 11 10]
  [ 1 11  4 13  7]]

 [[ 8  3  3  3 11]
  [ 8  4  7  1 13]]

 [[14 15  3 14 11]
  [ 1 15  2 12  7]]]
