In [1]:
# Exercise 5: Split, Concateneate, reshape arrays

In [2]:
import numpy as np

In [4]:
## Q1: Generate an array with integers 1-50

In [6]:
arr_one = np.arange(1,51)
print("First array:\n", arr_one)

First array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [4]:
## Q2: Generate an array with integers 51-100

In [7]:
arr_two = np.arange(51, 101)
print("First array:\n", arr_two)

First array:
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [8]:
## Q3: Concatenate the two arrays

In [9]:
arr_conc = np.concatenate([arr_one, arr_two])
print("The joined array:\n", arr_conc)

The joined array:
 [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [10]:
## Q4: Reshaping the joined array

In [12]:
arr_reshaped = arr_conc.reshape(10,10)
print("The reshaped combined array:\n", arr_reshaped)

The reshaped combined array:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
